# Generated by Django 5.1.4 on 2025-09-11 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(blank=True, default='0000000', null=True, unique=True)),
                ('reg', models.IntegerField(blank=True, default='0000', null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.CharField(blank=True, default='2020-2021', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
