# Generated by Django 5.1.4 on 2025-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='roll',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
