# Generated by Django 5.1.4 on 2025-09-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_account_reg_alter_account_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
