# Generated by Django 5.1.4 on 2025-09-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_department_subject_alter_account_reg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
