# Generated by Django 5.1.4 on 2025-09-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_teacher_name_profile_teacher_profile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Seacher')], max_length=100),
        ),
    ]
