# Generated by Django 5.1.4 on 2025-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teaher',
            field=models.ManyToManyField(blank=True, related_name='students', to='app1.teacher'),
        ),
    ]
