# Generated by Django 5.1.4 on 2025-09-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
       
        
    ]
