# Generated by Django 5.1.4 on 2025-09-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_student_new_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='new_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
    ]
