# Generated by Django 5.1.4 on 2025-09-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_student_new_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
