# Generated by Django 5.1.4 on 2025-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='app1/media/student/document'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='app1/media/student_photo/'),
        ),
    ]
