# Generated by Django 5.1.4 on 2025-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_student_document_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
